### PR TITLE
small style enhancements and systax corrections

### PR DESCRIPTION
**Pull request by shivarajnaidu**
Hi friends , I did small corrections and style code cleanups.. please review them and merge in upstream code and still lot of syntax errors are there..

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi,

I don't agree with changing absolute paths into relative paths.

**Comment by shivarajnaidu** [comment]
friend why you wont agree ? anything wrong or ill effect because of that relative paths.. ?
If so , please let me know..
and say for example .. when you open **`/home/user/github/linuxmint.github.io/reference/index.html`**  that file contains image  `` but actually the image is present at **`/home/user/github/linuxmint.github.io/logo.svg`**  . so when i open the **index.html** in browser image failed to load even styles too.. that's why i have changed them like relative paths and did some style edits/corrections also .. please review them too sir.

**Comment by clefebvre** [comment]
Hi,

Sorry for not justifying my comment. I should have explained why.

Code can be factorized, included, searched/replaced and so as much as possible identical code should remain identical. Depending on the location of the html file, the relative path to a resource might differ, whereas it will always be the same if you use absolute paths.

To view the pages locally you just need to run a local http server. If there was any server-side dynamism here, you would need that anyway.

**Comment by shivarajnaidu** [comment]
:+1: thank you very much for your kind response .

**Comment by shivarajnaidu** [comment]
Sir , shall I make any style changes here ? 
And please note that in my previous pull request ,I also made some CSS changes/corrections please review them and if that changes are good then please merge that with master branch.. I like and very glad to contribute in Linux mint website. I want to see some more improvements on website. Because website would give first impression to users . :blush:

**Comment by clefebvre** [comment]
Hi,

Thanks for your help. It's much appreciated. We need a website redesign for linuxmint.com and associated websites, we're hoping to tackle this after the release of Linux Mint 18.

Regarding the pull request, can you switch the paths back to absolute? the remaining changes could be merged then.

**Comment by shivarajnaidu** [comment]
:+1: :blush:

**Pull request closed without merging**
